### ISSUE TITLE
ReArrange

### ISSUE THREAD

**Issue by naxingyu** [dophist/nnet-conversion#1]
Training this kind of convnet requires a component called "<ReArrange>"? I suppose it is used copy the overlapped sub-bands? Is there a Kaldi patch for this?

**Comment by dophist** [comment]
* for 40-dim fbank filter [1 - 40]
it divides the input matrix into 8 matrices (8 parallel components)
* band 1: [1 ~ 6]
* band 2: [6 ~ 11]
* band 3: [11 ~ 16]
* band 4: [16 ~ 21]
* band 5: [21 ~ 26]
* band 6: [26 ~ 31]
* band 7: [31 ~ 36]
* band 8: [**35** ~ 40]

I don't have a working server, otherwise I could have presented you a text format model : )

**Comment by naxingyu** [comment]
Thanks Jerry. I understand the sub-band definitions. My question is, do 
I need a ReArangeComponent to do this before ParallelComponent.
The original Parallel component in Kaldi/nnet seem not supporting 
overlapping.

**Comment by dophist** [comment]
the rearrange component is just a copy operation, 1 matrix is copied into 8 smaller matrices, after that, a parallel component of 8 nnets processes 8 input matrices separately.

**Comment by naxingyu** [comment]
Got it.
